version: '3.4'
services:
  app:
    container_name: fireflyiii_app
    image: fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ../.env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: fireflyiii_db
    image: mariadb    
    hostname: fireflyiiidb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - firefly_iii_db:/var/lib/mysql

  openbudgeteer:
    container_name: openbudgeteer
    image: axelander/openbudgeteer:latest
    restart: unless-stopped
    environment:
      - Connection:Provider=sqlite
    ports:
      - 6100:80
    volumes:
      - ${ROOT}/config/openbudgeteer:/app/database

volumes:
   firefly_iii_upload:
   firefly_iii_db:
